version: "3.4"

services:
  cloudlog:
    build:
      context: ./cloudlog
      dockerfile: Dockerfile
    stop_signal: SIGKILL
    volumes:
      - cloudlog_data:/cloudlog
    env_file:
      - prod.env
  web:
    image: nginx:latest
    ports:
      - 8200:80
    volumes:
      - cloudlog_data:/cloudlog
      - ./nginx:/etc/nginx/conf.d
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - cloudlog_data:/cloudlog
  db:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - prod.env

volumes:
  cloudlog_data:
  mysql_data:
