version: "3.4"

services:
  cloudlog:
    build:
      context: ./cloudlog
      dockerfile: Dockerfile
    ports:
      - 8200:80
    env_file:
      - prod.env
  db:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - prod.env

volumes:
  mysql_data:
