version: "3.4"

services:
  cloudlog:
    build:
      context: ./cloudlog
      dockerfile: Dockerfile
    volumes:
      - cloudlog_data:/var/www/html
    env_file:
      - prod.env
    ports:
      - 9005:80
    restart: always
  db:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - prod.env
    restart: always

volumes:
  cloudlog_data:
  mysql_data:
