version: "3.4"

services:
  cloudlog:
    build:
      context: ./cloudlog
      dockerfile: Dockerfile
    volumes:
      - html_data:/var/www/html
    ports:
      - 8200:80
    env_file:
      - prod.env
    restart: always
  db:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - prod.env
    restart: always

volumes:
  mysql_data:
  html_data:
